platform :ios, '8.0'
target 'ShareLock' do
    pod 'AFNetworking', '~> 3.0'
    pod 'CocoaLumberjack'
    pod 'IQKeyboardManager'
    pod 'MBProgressHUD'
    pod 'MJExtension'
    pod 'MJRefresh'
    pod 'SDWebImage' ,'~> 3.7.0'
    pod 'Reachability'
#    pod 'BaiduMapKit'

    pod 'AMap3DMap'
    pod 'AMapSearch'
    pod 'AMapLocation'
    pod 'AMapNavi'
#    pod 'Masonry'

end
